

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# MySQL 설정 예시 (H2 대신 사용 시 주석 해제)
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/your_database_name
#     username: your_username
#     password: your_password
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

jwt:
  secret: your_jwt_secret_key_that_is_at_least_256_bits_long_and_very_secure
  expiration: 86400000 # 24 hours in milliseconds

